name: Dynamic_telegalaxy_Client_Worker_Installation

cleaninterval: 1000*60

hotpatch:
  - https://cdn.jsdelivr.net/npm/clientworker@latest
  - https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/cw.js
  - https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/cw.js

hotconfig:
  - https://raw.githubusercontent.com/telegalaxy/cwhotconfig/main/config.yaml

catch_rules:
  - rule: _
    transform_rules:
      - search: \#.*
        searchin: url
        replace: ''
      - search: \?.*
        replace: ''
      - search: \.html$
        header:
          Content-Type: text/html;charset=utf-8
      - search: _
        action: fetch
        fetch:
          engine: fetch # classic
          status: 200
          preflight: false
          timeout: 5000
          # cache:
          #   enable: true
          #   expire: 1000*60*60*365
      - search: (^4|^5)
        searchin: status
        action: return
        return:
          body: 呐呐呐~-欧尼酱~~页面不显示了，请联系管理员哦~~~
          status: 503

  - rule: ^https\:\/\/((cdn|fastly|gcore|quantil\test1)\.jsdelivr\.net\/gh)
    transform_rules:
      - search: _
        replace:
          - _
          - https://cdn.chuqis.com/gh
          - https://cdn2.chuqis.com/gh
          - https://cdn1.tianli0.top/gh

  - rule: ^https\:\/\/((cdn|fastly|gcore|quantil\test1)\.jsdelivr\.net\/npm|npm\.elemecdn\.com|unpkg\.com)
    transform_rules:
      - search: _
        replace:
          - _
          - https://code.bdstatic.com/npm
          - https://cdn.bilicdn.tk/npm     # 滥用封仓库 - GamerNoTitle
          - https://cdn.staticfile.org
          - https://npm.elemecdn.com
          - https://npm.sourcegcdn.com
          - https://unpkg.zhimg.com       # 滥用封仓库 - 知乎
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false
          timeout: 3000
          cache:
            expire: 1000*60*60*8
            delay: 300

  - rule: ^https\:\/\/cdnjs\.cloudflare\.com\/ajax\/libs
    transform_rules:
      - search: _
        replace:
          - _
          - https://cdn.bootcdn.net/ajax/libs
          - https://cdn.staticfile.org
          - https://cdnjs.sourcegcdn.com/ajax/libs          # 全同步 https://cdnjs.cloudflare.com
          - https://lib.baomitu.com
          - https://mirrors.cqupt.edu.cn/cdnjs/ajax/libs    # 重庆邮电
          - https://mirrors.sustech.edu.cn/cdnjs/ajax/libs  # 南大
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false
          timeout: 3000
          cache:
            expire: 1000*60*60*8
            delay: 300

  - rule: _
    transform_rules:
      - search: hm\.baidu\.com
        action: skip
